name: ckthing
favicon: null
layout_spectrum: 0.4162995961960405
typography_spectrum: 0.24089
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#55d400'
    - '#338000'
    - '#c9c9c9'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
